services:
  planning-server:
    image: ghcr.io/chamilton0/planning-server:0.1.0
    restart: always
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=user
      - MONGO_PASSWORD=password

  planning-ui:
    image: ghcr.io/chamilton0/planning-ui:0.0.1
    restart: always
    ports:
      - 80:80
    environment:
      - PLANNING_SERVER_HOST=planning-server
      - PLANNING_SERVER_PORT=8000
    volumes:
      - "${HTPASSWD_FILE:-/etc/nginx/.htpasswd}:/etc/nginx/.htpasswd"

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
