name: Android CI

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: bump version code
        run: ./.github/scripts/bumpVersion.sh

      - name: commit version changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Version CI'
          git config --global user.email 'chamilton0@users.noreply.github.com'
          git commit -am "ci(version): updates version"
          git push --force

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Version
        id: version
        working-directory: ./
        run: |
          version=$(grep -oP 'version = \s*"\K[^"\047]+' pyproject.toml | head -n 1)
          echo "Extracted version: $version"
          echo "release_version=$version" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.version.outputs.release_version }}

      - name: Tag commit
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: v${{ steps.version.outputs.release_version }}
